export type VeiculoDatabase = {
  placa: string
  marca: string
  modelo: string
  motor: string
  ano: string
  combustivel: string
  pecas: Array<{
    nome: string
    marca: string
    codigo?: string
  }>
}

export const veiculosDatabase: VeiculoDatabase[] = [
  {
    placa: "ABC1234",
    marca: "Toyota",
    modelo: "Corolla",
    motor: "1.8 16V Flex",
    ano: "2020",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Dianteiro", marca: "Monroe", codigo: "AMT001" },
      { nome: "Pastilha de Freio", marca: "Bosch", codigo: "PAS002" },
      { nome: "Filtro de Ar", marca: "Mann", codigo: "FIL003" },
      { nome: "Óleo do Motor", marca: "Castrol", codigo: "OLE004" },
      { nome: "Vela de Ignição", marca: "NGK", codigo: "VEL005" },
      { nome: "Correia Dentada", marca: "Gates", codigo: "COR006" },
      { nome: "Disco de Freio", marca: "TRW", codigo: "DIS007" },
      { nome: "Filtro de Combustível", marca: "Mahle", codigo: "FIC008" },
      { nome: "Bateria", marca: "Moura", codigo: "BAT009" },
      { nome: "Pneu", marca: "Michelin", codigo: "PNE010" },
    ],
  },
  {
    placa: "BRA1E23",
    marca: "Honda",
    modelo: "Civic",
    motor: "2.0 16V",
    ano: "2019",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Traseiro", marca: "KYB", codigo: "AMT011" },
      { nome: "Pastilha de Freio", marca: "Ferodo", codigo: "PAS012" },
      { nome: "Filtro de Ar", marca: "Wega", codigo: "FIL013" },
      { nome: "Óleo do Motor", marca: "Mobil", codigo: "OLE014" },
      { nome: "Vela de Ignição", marca: "Bosch", codigo: "VEL015" },
      { nome: "Correia do Alternador", marca: "Dayco", codigo: "COR016" },
      { nome: "Disco de Freio", marca: "Fremax", codigo: "DIS017" },
      { nome: "Filtro de Óleo", marca: "Tecfil", codigo: "FIC018" },
      { nome: "Bateria", marca: "Heliar", codigo: "BAT019" },
      { nome: "Pneu", marca: "Pirelli", codigo: "PNE020" },
    ],
  },
  {
    placa: "DEF5678",
    marca: "Volkswagen",
    modelo: "Golf",
    motor: "1.4 TSI",
    ano: "2021",
    combustivel: "Gasolina",
    pecas: [
      { nome: "Amortecedor Dianteiro", marca: "Sachs", codigo: "AMT021" },
      { nome: "Pastilha de Freio", marca: "ATE", codigo: "PAS022" },
      { nome: "Filtro de Ar", marca: "Mahle", codigo: "FIL023" },
      { nome: "Óleo do Motor", marca: "Liqui Moly", codigo: "OLE024" },
      { nome: "Vela de Ignição", marca: "NGK", codigo: "VEL025" },
      { nome: "Correia Dentada", marca: "Continental", codigo: "COR026" },
      { nome: "Disco de Freio", marca: "Zimmermann", codigo: "DIS027" },
      { nome: "Filtro de Combustível", marca: "Bosch", codigo: "FIC028" },
      { nome: "Bateria", marca: "Varta", codigo: "BAT029" },
      { nome: "Pneu", marca: "Continental", codigo: "PNE030" },
    ],
  },
  {
    placa: "GHI9012",
    marca: "Ford",
    modelo: "Focus",
    motor: "2.0 16V",
    ano: "2018",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Dianteiro", marca: "Monroe", codigo: "AMT031" },
      { nome: "Pastilha de Freio", marca: "Jurid", codigo: "PAS032" },
      { nome: "Filtro de Ar", marca: "Fram", codigo: "FIL033" },
      { nome: "Óleo do Motor", marca: "Valvoline", codigo: "OLE034" },
      { nome: "Vela de Ignição", marca: "Motorcraft", codigo: "VEL035" },
      { nome: "Correia Dentada", marca: "Gates", codigo: "COR036" },
      { nome: "Disco de Freio", marca: "Brembo", codigo: "DIS037" },
      { nome: "Filtro de Combustível", marca: "Purflux", codigo: "FIC038" },
      { nome: "Bateria", marca: "AC Delco", codigo: "BAT039" },
      { nome: "Pneu", marca: "Goodyear", codigo: "PNE040" },
    ],
  },
  {
    placa: "JKL3456",
    marca: "Chevrolet",
    modelo: "Onix",
    motor: "1.0 12V",
    ano: "2022",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Traseiro", marca: "Cofap", codigo: "AMT041" },
      { nome: "Pastilha de Freio", marca: "Fras-le", codigo: "PAS042" },
      { nome: "Filtro de Ar", marca: "Tecfil", codigo: "FIL043" },
      { nome: "Óleo do Motor", marca: "GM", codigo: "OLE044" },
      { nome: "Vela de Ignição", marca: "AC Delco", codigo: "VEL045" },
      { nome: "Correia do Alternador", marca: "Contitech", codigo: "COR046" },
      { nome: "Disco de Freio", marca: "Hipper", codigo: "DIS047" },
      { nome: "Filtro de Óleo", marca: "Mann", codigo: "FIC048" },
      { nome: "Bateria", marca: "Zetta", codigo: "BAT049" },
      { nome: "Pneu", marca: "Bridgestone", codigo: "PNE050" },
    ],
  },
  {
    placa: "MNO7890",
    marca: "Hyundai",
    modelo: "HB20",
    motor: "1.6 16V",
    ano: "2021",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Dianteiro", marca: "Mando", codigo: "AMT051" },
      { nome: "Pastilha de Freio", marca: "Sangsin", codigo: "PAS052" },
      { nome: "Filtro de Ar", marca: "Hyundai", codigo: "FIL053" },
      { nome: "Óleo do Motor", marca: "Shell", codigo: "OLE054" },
      { nome: "Vela de Ignição", marca: "Denso", codigo: "VEL055" },
      { nome: "Correia Dentada", marca: "Dayco", codigo: "COR056" },
      { nome: "Disco de Freio", marca: "Mando", codigo: "DIS057" },
      { nome: "Filtro de Combustível", marca: "Wega", codigo: "FIC058" },
      { nome: "Bateria", marca: "Cral", codigo: "BAT059" },
      { nome: "Pneu", marca: "Hankook", codigo: "PNE060" },
    ],
  },
  {
    placa: "PQR1234",
    marca: "Nissan",
    modelo: "Versa",
    motor: "1.6 16V",
    ano: "2020",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Traseiro", marca: "KYB", codigo: "AMT061" },
      { nome: "Pastilha de Freio", marca: "Akebono", codigo: "PAS062" },
      { nome: "Filtro de Ar", marca: "Nissan", codigo: "FIL063" },
      { nome: "Óleo do Motor", marca: "Nissan", codigo: "OLE064" },
      { nome: "Vela de Ignição", marca: "NGK", codigo: "VEL065" },
      { nome: "Correia do Alternador", marca: "Gates", codigo: "COR066" },
      { nome: "Disco de Freio", marca: "Nissan", codigo: "DIS067" },
      { nome: "Filtro de Óleo", marca: "Fram", codigo: "FIC068" },
      { nome: "Bateria", marca: "Yuasa", codigo: "BAT069" },
      { nome: "Pneu", marca: "Yokohama", codigo: "PNE070" },
    ],
  },
  {
    placa: "STU5678",
    marca: "Fiat",
    modelo: "Argo",
    motor: "1.3 8V",
    ano: "2019",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Dianteiro", marca: "Magneti Marelli", codigo: "AMT071" },
      { nome: "Pastilha de Freio", marca: "Brembo", codigo: "PAS072" },
      { nome: "Filtro de Ar", marca: "Magneti Marelli", codigo: "FIL073" },
      { nome: "Óleo do Motor", marca: "Selenia", codigo: "OLE074" },
      { nome: "Vela de Ignição", marca: "Champion", codigo: "VEL075" },
      { nome: "Correia Dentada", marca: "Dayco", codigo: "COR076" },
      { nome: "Disco de Freio", marca: "Magneti Marelli", codigo: "DIS077" },
      { nome: "Filtro de Combustível", marca: "Purflux", codigo: "FIC078" },
      { nome: "Bateria", marca: "Fiamm", codigo: "BAT079" },
      { nome: "Pneu", marca: "Pirelli", codigo: "PNE080" },
    ],
  },
  {
    placa: "VWX9012",
    marca: "Renault",
    modelo: "Sandero",
    motor: "1.0 12V",
    ano: "2021",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Traseiro", marca: "Monroe", codigo: "AMT081" },
      { nome: "Pastilha de Freio", marca: "Ferodo", codigo: "PAS082" },
      { nome: "Filtro de Ar", marca: "Renault", codigo: "FIL083" },
      { nome: "Óleo do Motor", marca: "Elf", codigo: "OLE084" },
      { nome: "Vela de Ignição", marca: "Renault", codigo: "VEL085" },
      { nome: "Correia do Alternador", marca: "Continental", codigo: "COR086" },
      { nome: "Disco de Freio", marca: "TRW", codigo: "DIS087" },
      { nome: "Filtro de Óleo", marca: "Mann", codigo: "FIC088" },
      { nome: "Bateria", marca: "Tudor", codigo: "BAT089" },
      { nome: "Pneu", marca: "Michelin", codigo: "PNE090" },
    ],
  },
  {
    placa: "YZA3456",
    marca: "Peugeot",
    modelo: "208",
    motor: "1.2 12V",
    ano: "2020",
    combustivel: "Flex",
    pecas: [
      { nome: "Amortecedor Dianteiro", marca: "Sachs", codigo: "AMT091" },
      { nome: "Pastilha de Freio", marca: "Bosch", codigo: "PAS092" },
      { nome: "Filtro de Ar", marca: "Peugeot", codigo: "FIL093" },
      { nome: "Óleo do Motor", marca: "Total", codigo: "OLE094" },
      { nome: "Vela de Ignição", marca: "Bosch", codigo: "VEL095" },
      { nome: "Correia Dentada", marca: "Gates", codigo: "COR096" },
      { nome: "Disco de Freio", marca: "Bosch", codigo: "DIS097" },
      { nome: "Filtro de Combustível", marca: "Purflux", codigo: "FIC098" },
      { nome: "Bateria", marca: "Varta", codigo: "BAT099" },
      { nome: "Pneu", marca: "Michelin", codigo: "PNE100" },
    ],
  },
]
